server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:ing-keystore.p12
    key-store-password: '@lphaPass4ord'
    key-password: '@lphaPass4ord'
    protocol: TLS
    enabled-protocols: TLSv1.2
logging:
  level:
    org.springframework: trace