server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:ing-keystore.p12
    key-store-password: '@lphaPass4ord'
    key-password: '@lphaPass4ord'
    protocol: TLS
    enabled-protocols: TLSv1.2
logging:
  level:
    org.springframework: trace
app:
  security:
    jwt:
      secretKey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1gsAvHdgcz0QqRSlD+AijYbwVHFNfYSc0xxLdCxNqJbYug/rNb07OKTwF810Q+j5L09qFFsODIU/FlovKQdulZertmUFFiOAp6Gk4Z2pTkHqfu8EwGgPkLzsBEp+G8lralmII7DpdKd84mlK1/0s/TdbI4CxkakgO2ROiEthRWUeQCUzNpzYZRNFNwzLNWHvBw3Estsfa8l1Y32ZAJYZmCXk8mSprJfJPJbOVxSW3rYZCf8uEO2UMnaB+Z/yZakBNPXt34qUAMW5LNErIxsX0pv69UgGwUwAWb0TT5YnJjHfpDt/rJOVc7thCJ8oXq5a7XEhNe5oK0VLiLMA9HYAaQIDAQAB'
      expirationDuration: 600000 #10 minutes = 10 * 60 * 1000 ms